### ISSUE TITLE
Problems with many accounts and reconecting to the stream

### ISSUE THREAD

**Issue by Al0shka228** [gottagofaster236/Twitch-Channel-Points-Miner#33]
When i start script many times. Its work ok. But when streamer stop stream. Bot says. Streamer offline currently and stop checking the accounts. When streamer start again bot do not start again. When i restart it i get errors https://prnt.sc/wkcx88
Only 2 scripts of 18 contine working
Can you help me with it?)

**Comment by Al0shka228** [comment]
When i delete all files and login again. It get new cookie and work well until it stop working. Maybe the trouble with the cookie. If you need i can give you cookie that have that problem

**Comment by jhagin002** [comment]
I'm not very familiar with the code, so someone might have to correct me but I'm pretty sure that the error that you are getting is because when the script makes the get request to the Twitch API with the headers of your authorization token, what is returned from the API does not include the "data" value. The get request should return a response that looks like this:

> {
    "data": [{
        "id": "44322889",
        "login": "dallas",
        "display_name": "dallas",
        "type": "staff",
        "broadcaster_type": "",
        "description": "Just a gamer playing games and chatting. :)",
        "profile_image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/dallas-profile_image-1a2c906ee2c35f12-300x300.png",
        "offline_image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/dallas-channel_offline_image-1a2c906ee2c35f12-1920x1080.png",
        "view_count": 191836881,
        "email": "login@provider .com"
    }]
}
*###response example from https://dev.twitch.tv/docs/api/reference#get-users*

This could mean that when the get request is made with the authorization token that was received from the 'get_auth_token()' function, which gets the authorization token from the cookies file, the API could be returning a response of:

> {"error":"Unauthorized","status":401,"message":"OAuth token is missing"}

or a response of:

> {"error":"Unauthorized","status":401,"message":"Invalid OAuth token"}

Now I'm not understanding what you mean by you are having problems with "many accounts." Are you logging into multiple accounts to try to get channel points for all of them? If so, are you running the same script from the same path, or do you have multiple copies of the "Twitch-Channel-Points-Master" folder and logging into each account from the different instances of cmd.exe with each having different paths to main.py?

**Comment by gottagofaster236** [comment]
Wait, are you trying to log in from multiple accounts? I would suggest you copy the entire directory with the program to some other place, and login again from that copy.

**Comment by Al0shka228** [comment]
Thanks. I just copy the directory and all works well
